# Generated by Django 4.0.8 on 2022-12-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_testmodel_created_at_testmodel_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
